services:
  face_analysis_basic:
    build: .
    container_name: face_analysis_basic
    ports:
      - "8001:8001"  # BASIC API
    environment:
      - MAX_IMAGE_SIZE=2048
    volumes:
      - ./eyelid_model.onnx:/app/eyelid_model.onnx:ro
      - ./eyelid_model.onnx.data:/app/eyelid_model.onnx.data:ro
    command: ["uvicorn", "Face_analyzer_BASIC:app", "--host", "0.0.0.0", "--port", "8001"]
    restart: always

  face_analysis_pro:
    build: .
    container_name: face_analysis_pro
    ports:
      - "8002:8002"  # PRO API
    environment:
      - MAX_IMAGE_SIZE=2048
    volumes:
      - ./eyelid_model.onnx:/app/eyelid_model.onnx:ro
      - ./eyelid_model.onnx.data:/app/eyelid_model.onnx.data:ro
    command: ["uvicorn", "Face_analyzer_PRO:app", "--host", "0.0.0.0", "--port", "8002"]
    restart: always
