const fs = require('fs');
const vm = require('vm');
const assert = require('assert/strict');
const src = fs.readFileSync(require('path').join(__dirname, '../js/router.js'), 'utf8');
const start = src.indexOf('const trainParts =');
const end = src.indexOf('// 訓練前後對照', start);
assert(start > 0 && end > start);
const old = (id, time, value, extra = {}) => ({runId:id,status:'done',finishedAt:time,
  model:'ConvNeXt-Tiny', evaluationSetId:'set-a',modelAfter:{parts:{face_shape:{macroAccuracy:value}}},...extra});
const records = [old('old','2026-08-01',0.6), old('nearest','2026-08-03',0.7),
  old('future','2026-08-05',0.99), old('wrong-set','2026-08-03T01:00:00Z',0.98,{evaluationSetId:'set-b'})];
const ctx = {TRAIN_PART_ZH:{face_shape:'臉型',eye_shape:'眼型'},fbRunRecords:new Map(records.map(r=>[r.runId,r]))};
vm.runInNewContext(src.slice(start,end)+'globalThis.fill=trainHistoricalBefore; globalThis.macro=trainMacro;',ctx);
const run = {runId:'current',model:'ConvNeXt-Tiny',evaluationSetId:'set-a',startedAt:'2026-08-04',modelBefore:{parts:{eye_shape:{macroAccuracy:0.8}}}};
const snapshot=JSON.stringify(run);
assert.equal(ctx.fill(run).parts.face_shape.macroAccuracy,0.7);
assert.equal(ctx.fill(run).parts.face_shape.historicalRunId,'nearest');
assert.equal(ctx.fill(run).parts.eye_shape.macroAccuracy,0.8);
assert.equal(JSON.stringify(run),snapshot);
assert.equal(ctx.fill({...run,evaluationSetId:null}).parts.face_shape,undefined);
assert.equal(ctx.fill({...run,model:'Other'}).parts.face_shape,undefined);
assert.equal(ctx.macro({macroAccuracy:null}),null);
assert.equal(ctx.macro({macroAccuracy:0}),0);
assert.equal(ctx.macro({macroAccuracy:2}),null);
run.modelBefore.parts.face_shape={macroAccuracy:0.5};
assert.equal(ctx.fill(run).parts.face_shape.macroAccuracy,0.5);
console.log('PASS macro history: nearest earlier comparable record, preserve existing/zero, no mutation, missing metadata rejected');
ctx.TRAIN_PART_ZH = {face_shape:'臉型',brow_shape:'眉型',eye_shape:'眼型',nose_shape:'鼻型',lip_shape:'唇型'};
ctx.escapeHtml = s => String(s).replace(/</g,'&lt;').replace(/>/g,'&gt;');
const deltaStart = src.indexOf('const trainDeltaHtml =');
const deltaEnd = src.indexOf('// 這個批次送了哪些部位', deltaStart);
vm.runInNewContext(src.slice(deltaStart,deltaEnd)+'globalThis.delta=trainDeltaHtml;',ctx);
const missingHtml = ctx.delta({},{});
assert.equal((missingHtml.match(/class="atb-delta-row"/g)||[]).length,5);
for (const label of Object.values(ctx.TRAIN_PART_ZH)) assert(missingHtml.includes(label));
assert.equal(ctx.macro({accuracy:0.99}),null);
const summaryStart = src.indexOf('const renderTrainingRuns =');
const summaryEnd = src.indexOf('if (!fbRuns) return;',summaryStart);
ctx.fbTrainingPanel={}; ctx.fbCurrentScore={};
vm.runInNewContext(src.slice(summaryStart,summaryEnd)+'}; globalThis.summary=renderTrainingRuns;',ctx);
ctx.summary({currentMetrics:{architecture:'ConvNeXt-Tiny',evaluationSetId:'set-a',parts:{eye_shape:{macroAccuracy:0.8}}},runs:records.slice(0,2)});
for (const label of Object.values(ctx.TRAIN_PART_ZH)) assert(ctx.fbCurrentScore.textContent.includes(label));
assert(ctx.fbCurrentScore.textContent.includes('歷史值｜來源批次：nearest'));
assert(ctx.fbCurrentScore.textContent.includes('眼型 80.0%'));
assert(ctx.fbCurrentScore.textContent.includes('唇型 未記錄'));
assert(!ctx.fbCurrentScore.textContent.includes('線上模型'));
console.log('PASS five-part rows and summary, historical source, macro only, no online claim');
